from mongoengine import *

connect(host='mongodb://localhost:27017/qq')

class User(Document):
    _id = IntField(),
    current_task_idx = IntField(),
    status = StringField(),
    name = StringField(),
    age = StringField(), 
    gender =StringField(),
    learned_words = ListField(),
    wrong_answered_words = ListField(),
    command = ListField(),
    lang = StringField(),
    city = StringField(),
    ttime = ListField(),
    aver_resp_time = ListField(),
    wrong_idx_french = ListField(),
    right_idx_french = ListField(),
    wrong_idx_eng = ListField(),
    right_idx_eng = ListField(),
    wrong_idx_chinese = ListField(),
    right_idx_chinese = ListField(),
    wrong_idx_german = ListField(),
    right_idx_german = ListField(),
    wrong_idx_czech = ListField(),
    right_idx_czech = ListField(),
    last_day_count = ListField(),
    current_day_count = ListField(),
    last_week_count = ListField(),
    current_week_count = ListField(),
    last_month_count = ListField(),
    current_month_count = ListField(), 
    wrong_answered_last_day = ListField(),
    wrong_answered_current_day = ListField(),
    wrong_answered_last_week = ListField(),
    wrong_answered_current_week = ListField(),
    wrong_answered_last_month = ListField(),
    wrong_answered_current_month = ListField(),
    aver_time_last_day = ListField(),
    aver_time_current_day = ListField(),
    aver_time_last_week = ListField(),
    aver_time_current_week = ListField(),
    aver_time_last_month = ListField(),
    aver_time_current_month = ListField(),
    diff = StringField()

# ross = User(email='ross@example.com', first_name='Ross', last_name='Lawley').save()